// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH0sHfxt4qhWtKqkwW3oWETZah4VwRwSk',
    appId: '1:137940009532:web:27bd8cf6b7254b73053939',
    messagingSenderId: '137940009532',
    projectId: 'sehatmakaan-833e2',
    authDomain: 'sehatmakaan-833e2.firebaseapp.com',
    storageBucket: 'sehatmakaan-833e2.firebasestorage.app',
    measurementId: 'G-EZ63T60DHD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoOM9HtC09HcTmOFLoDronUjBho3IHjHI',
    appId: '1:137940009532:android:ac7d84b1dcbb7c82053939',
    messagingSenderId: '137940009532',
    projectId: 'sehatmakaan-833e2',
    storageBucket: 'sehatmakaan-833e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6KE-ObsNmaU_SkNZiEbpzY_rq7q_xVN4',
    appId: '1:137940009532:ios:5c5ebd24c1ed8eea053939',
    messagingSenderId: '137940009532',
    projectId: 'sehatmakaan-833e2',
    storageBucket: 'sehatmakaan-833e2.firebasestorage.app',
    iosBundleId: 'com.sehatmakaan.sehatMakaanFlutter',
  );
}
